// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pzfsckmxjhikculhtclf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB6ZnNja214amhpa2N1bGh0Y2xmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0MTg2MzMsImV4cCI6MjA2ODk5NDYzM30.iuD1npIOidegkdAnRY4Wfu6iMwi3oTIgYILqCJ0NWgs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});